### ISSUE TITLE
Stuck sitting down after /home

### ISSUE THREAD

**Issue by everamzah** [kilbith/xdecor#17]
If while sitting in a chair/cushion a player teleports /home, they will become stuck in place, in a sitting position.

**Comment by kilbith** [comment]
I knew this issue, and I have no way to fix since I can't check whether a player is teleported or attempt to be teleported. Sorry.

**Comment by MT-Modder** [comment]
Maybe you can check if the player pos is different, or far, from the chair/cushion pos.
