### ISSUE TITLE
New item from "cut" menu in worktable don't replace item in full player inventory

### ISSUE THREAD

**Issue by amadin** [kilbith/xdecor#18]
If you have full inventory and you trying to replace item with a new item from "cut" menu, it will don't work.
![screenshot_20151203_214810](https://cloud.githubusercontent.com/assets/13412191/11572247/23d14db2-99f8-11e5-9791-ad0ab7f66019.png)

Mod was download today.

**Comment by kilbith** [comment]
Yes it's intentional (since https://github.com/kilbith/xdecor/commit/22cf219ca9884eb7e896227295bd7bfae7c31e13), because before it replaced the stack in your inventory when your inventory was full (see this report : https://forum.minetest.net/viewtopic.php?p=198882#p198882).
