### ISSUE TITLE
I think hive produce honey too fast

### ISSUE THREAD

**Issue by amadin** [kilbith/xdecor#20]
I think hive produce honey too fast. In reall world beekeeper can take honey once a year. Hive in xdecor inexpensive. Now the player is enough just of one beehive but will be good if player will need create apiary.

**Comment by kilbith** [comment]
OK, will make it slower.

**Comment by kilbith** [comment]
https://github.com/kilbith/xdecor/commit/d3bdb95ccddba737290b60f9d930c3b764c7d48f

I hope it's better.
