### ISSUE TITLE
Crash related to the enchantment table

### ISSUE THREAD

**Issue by ChaosWormz** [kilbith/xdecor#22]
2016-01-21 14:32:15: ERROR[Main]: ServerError: Lua: Runtime error from mod 'xdec
or' in callback node_on_receive_fields(): ...e/cwz/worlds/tt_survival/worldmods/
xdecor/enchanting.lua:60: attempt to concatenate local 'name' (a nil value)
2016-01-21 14:32:15: ERROR[Main]: stack traceback:
2016-01-21 14:32:15: ERROR[Main]:       ...e/cwz/worlds/tt_survival/worldmods/xd
ecor/enchanting.lua:60: in function <...e/cwz/worlds/tt_survival/worldmods/xdeco
r/enchanting.lua:53>

**Comment by kilbith** [comment]
You're using an outdated copy of xdecor.

Try updating and if it keeps crashing, give me a way to reproduce if possible.

**Comment by kilbith** [comment]
So, no further informations ? If not, I'm about to close this.
