### ISSUE TITLE
Bug with buckets and cauldrons

### ISSUE THREAD

**Issue by Ombridride** [kilbith/xdecor#23]
Hi, im here to report a bug to you, first an IRC discussion :
```
R_R_E_Designs : Cauldron is to cook. You can make soup in it.
ihatedrift : whaaaat
R_R_E_Designs : But it doesn't work. We tried with gravgun.
MinetestForFun : Why it doesn't work ?
R_R_E_Designs : He thinks it's due to buckets now working with right clik. Because you can't fill it with water.
R_R_E_Designs : Right clicking places a node of water, as normal, but doesn't fill the cauldron.
MinetestForFun : Oh, yes, that's a good point, I report it to kilbith
```

Like @rredesigns reported it to us, we met a problem with cauldrons when bucket working with right click, indeed we can't fill cauldrons is this case.

Please, can you add to your mod a way to fix it and, in the better case, add a *minetest.conf* option to activate the right click filling with bucket or not for your cauldrons ?

Thank you in advance,

**Comment by kilbith** [comment]
On peut se parler français hein ;)

A mon avis tu dois utiliser une version modifiée de `buckets` ou avoir un override quelque part sur ses items, car je peux très bien remplir un chaudron vide avec un seau d'eau (et le vider avec un seau vide). Ça marche très bien sur les autres serveurs aussi.

**Comment by Ombridride** [comment]
Ok parlons français :)

Alors c'est un soucis ciblé sur le serveur Skyblock, et qui tourne donc princiaplement avec le subgame du même nom, c'est sans nul doute un soucis lié à cela.

Oui la version de buckets est une version modifié.

Bon si ce n'est pas un soucis de clique gauche/droit pour prendre/remplir un liquide, il va nous falloir chercher les overrides comme tu le dis, je te tiens au courant.

**Comment by kilbith** [comment]
Je ferme ce ticket en attendant. Si tu souhaites le ré-ouvrir, fais-le moi savoir.

**Comment by LeMagnesium** [comment]
Tout ça venait d'une réécriture du callback `on_use` des buckets qui ne cherchait pas à exécuter les callbacks `on_rightclick` lorsqu'on utilise le bucket sur un node.
Tout est résolu, ça venait de Skyblock.
