### ISSUE TITLE
Right clicking shape with tool removes tool

### ISSUE THREAD

**Issue by everamzah** [kilbith/xdecor#26]

**Comment by kilbith** [comment]
Please define "shape" ? And if possible, a clear way to reproduce.

**Comment by kilbith** [comment]
Fixed with https://github.com/kilbith/xdecor/commit/5943d5ef1323ff53b23f3abd61d113752a25a542, assuming "shape" means a nodebox node from the Work Table.

**Comment by everamzah** [comment]
Yes.  I will try to be more clear in the future.  Thank you for the quick
fix!

**Comment by kilbith** [comment]
Actually, pick this one : https://github.com/kilbith/xdecor/commit/e74d164958da879efdec3d94ccc94f97b09ae6e6
