### ISSUE TITLE
Enchantment table crash server if press button after enchantment

### ISSUE THREAD

**Issue by amadin** [kilbith/xdecor#27]
If you enchanted some tool then quick move it to inventory and press button again - server will crash. 0.4.13.

2016-02-04 22:11:42: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
2016-02-04 22:11:42: ERROR[main]: Lua: Runtime error from mod 'xdecor' in callback node_on_receive_fields(): ...r-13/minetest-rivergen/bin/../mods/xdecor/enchanting.lua:86: attempt to concatenate local 'name' (a nil value)
2016-02-04 22:11:42: ERROR[main]: stack traceback:
2016-02-04 22:11:42: ERROR[main]:       ...r-13/minetest-rivergen/bin/../mods/xdecor/enchanting.lua:86: in function <...r-13/minetest-rivergen/bin/../mods/xdecor/enchanting.lua:79>

In thread b7180700:
/mnt/sda3/minetest-master-13/minetest-rivergen/src/server.cpp:511: void Server::step(float): A fatal error occurred: Lua: Runtime error from mod 'xdecor' in callback node_on_receive_fields(): ...r-13/minetest-rivergen/bin/../mods/xdecor/enchanting.lua:86: attempt to concatenate local 'name' (a nil value)
stack traceback:
        ...r-13/minetest-rivergen/bin/../mods/xdecor/enchanting.lua:86: in function <...r-13/minetest-rivergen/bin/../mods/xdecor/enchanting.lua:79>
Debug stacks:
DEBUG STACK FOR THREAD b3dffb40:
#0  virtual void* EmergeThread::Thread()
(Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD b476bb40:
#0  virtual void* ServerThread::Thread()
#1  void Server::Receive()
(Leftover data: #2  void Server::SendBlocks(float))
(Leftover data: #3  void RemoteClient::GetNextBlocks(ServerEnvironment*, EmergeManager*, float, std::vector<PrioritySortedBlockTransfer>&))
(Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
(Leftover data: #5  bool getCraftingResult(Inventory*, ItemStack&, std::vector<ItemStack>&, bool, IGameDef*))
DEBUG STACK FOR THREAD b7180700:
#0  int main(int, char**)
#1  Dedicated server branch
#2  void dedicated_server_loop(Server&, bool&)
#3  void Server::step(float)

**Comment by kilbith** [comment]
https://github.com/kilbith/xdecor/commit/6a3b71d4b4e547a4fbe0239d3bddab88b10ab8d1
