### ISSUE TITLE
crashloop

### ISSUE THREAD

**Issue by tchncs** [kilbith/xdecor#29]
Hi, i updated as you requested and the server is falling into crashloop now ;)

```
Feb  5 22:48:14 lsw-minetest minetestserver[5548]: 2016-02-05 22:48:14: WARNING[Main]: Undeclared global variable "homedecor_register_slope" accessed at /home/minetest/minetest/bin/../mods/steel/steel/init.lua:196
Feb  5 22:48:14 lsw-minetest minetestserver[5548]: 2016-02-05 22:48:14: ERROR[Main]: ModError: Failed to load and run script from /home/minetest/tchncslsw/worldmods/xdecor/init.lua:
Feb  5 22:48:14 lsw-minetest minetestserver[5548]: 2016-02-05 22:48:14: ERROR[Main]: /home/minetest/tchncslsw/worldmods/xdecor/worktable.lua:348: attempt to index field 'tiles' (a nil value)
Feb  5 22:48:14 lsw-minetest minetestserver[5548]: 2016-02-05 22:48:14: ERROR[Main]: stack traceback:
Feb  5 22:48:14 lsw-minetest minetestserver[5548]: 2016-02-05 22:48:14: ERROR[Main]: #011/home/minetest/tchncslsw/worldmods/xdecor/worktable.lua:348: in main chunk
Feb  5 22:48:14 lsw-minetest minetestserver[5548]: 2016-02-05 22:48:14: ERROR[Main]: #011[C]: in function 'dofile'
Feb  5 22:48:14 lsw-minetest minetestserver[5548]: 2016-02-05 22:48:14: ERROR[Main]: #011/home/minetest/tchncslsw/worldmods/xdecor/init.lua:19: in main chunk
```

**Comment by kilbith** [comment]
That's because the Work Table has a new system for detecting which nodes are cuttable. 

Can you please disable your mods one-by-one (except xdecor) and see which mod triggers this crash, please ?

**Comment by tchncs** [comment]
Thanks for your fast answer! 
Looks like Bitchange is the bad one...ow i had luck to got the idea to search on the buttom of the list on this time im half on sleep :D 
(your mod is in the worldmods)

**Comment by kilbith** [comment]
OK, fixed : https://github.com/kilbith/xdecor/commit/a30d76fb488245a1a96f573976d3fd66888ced45

Some nodes in Bitchange used some deprecated definition. Thanks for reporting.

**Comment by tchncs** [comment]
Wonderful, thank you very much! :)

**Comment by tchncs** [comment]
Oh, now the stairs are broken :o 

![screenshot_20160206_000152](https://cloud.githubusercontent.com/assets/10698140/12861603/dd71ed3c-cc64-11e5-9f21-d0367ea1d878.png)

**Comment by kilbith** [comment]
Give me their node names please.

**Comment by tchncs** [comment]
Im not sure how... .
Its ```stairs:stair_cobble - default_cobble.png``` ... ...how can i give you the exact name if this isnt? 
We have [stairsplus](https://github.com/CasimirKaPazi/stairsplus/blob/master/stair.lua) ...

**Comment by kilbith** [comment]
Silly mistake, I missed some brackets. Fixed : https://github.com/kilbith/xdecor/commit/ab6514babd9cd0b202b118b825a43dca4dd09e8e

**Comment by tchncs** [comment]
nice, now all is looking fine, thank you very much again :+1:
