### ISSUE TITLE
Torches shouldn't float on top of xwalls.

### ISSUE THREAD

**Issue by Splizard** [kilbith/xdecor#30]
This looks ugly...
![screenshot_20160209_174027](https://cloud.githubusercontent.com/assets/2015791/12907786/4fb54046-cf54-11e5-8a3a-2c18dbd250a7.png)

**Comment by kilbith** [comment]
That's because the collision box is taller than the wall to prevent jumping over it.

**Comment by Splizard** [comment]
What I am getting at is if you can you add a corner piece where there is something above the wall. So there is something for the torch to go on?

**Comment by kilbith** [comment]
No, it would need an ABM to each wall part to check if there's something above. Too heavy.

Anyways I'll drop these walls soon since minetest_game will get cobblewalls using a more efficient method for placing : https://github.com/minetest/minetest_game/pull/796
