### ISSUE TITLE
servercrash with anvil

### ISSUE THREAD

**Issue by tchncs** [kilbith/xdecor#31]
```
ERROR[Main]: ServerError: Lua: Runtime error from mod 'xdecor' in callback nodemeta_inventory_AllowPut(): /home/minetest/minetest/bin/../mods/xdecor/worktable.lua:7: attempt to index local 'def' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: #011/home/minetest/minetest/bin/../mods/xdecor/worktable.lua:7: in function 'nodes'
ERROR[Main]: #011/home/minetest/minetest/bin/../mods/xdecor/worktable.lua:270: in function </home/minetest/minetest/bin/../mods/xdecor/worktable.lua:266>
```

a player did tryed to put the hammer in the place...and the server crashed.

**Comment by kilbith** [comment]
Are you sure to use the current code ? Because I can't reproduce your crash.

**Comment by kilbith** [comment]
Apparently fixed after updating.

**Comment by tchncs** [comment]
btw, it was the hammer of sokomines anvil mod, as i heared now :)
but its still all fine now.

**Comment by kilbith** [comment]
Only the xdecor's hammer is allowed to be put in the Work Table, and as always been.

So the crash is likely from Sokomine's anvil mod.
