### ISSUE TITLE
Information lacking

### ISSUE THREAD

**Issue by greencopper** [kilbith/xdecor#32]
Hi

It would be really great with some documentation about usage. For example sitting in the cushion, how does one get up again?

Looking in the code seems like "sneak" + "right click", or maybe I have misunderstood? Anyway, we're get stuck in a sitting position.

Otherwise, great mod, thanks a lot!

**Comment by kilbith** [comment]
Thank you. But I don't think it's worth writing a documentation as it's fairly easy to understand already.

Have fun.

**Comment by greencopper** [comment]
Well, we're stuck sitting and unless it's a buck some information about how to get up from a cushion or chair would be great!

**Comment by kilbith** [comment]
You get up from the cushion the same way as you sit.

**Comment by greencopper** [comment]
Then we have a bug!

**Comment by greencopper** [comment]
Neither right-clicking the cushion or what ever block surrounds it makes one get up. We're running Minetest 0.4.13 and testing xdecor on that.

**Comment by greencopper** [comment]
We have just tested it on a box with no other mods and it works there. So, sorry, there is some mod conflict on our server I guess. I don't know which mod screws this up, will report if I find out.

**Comment by kilbith** [comment]
What's the address of your server ?

**Comment by greencopper** [comment]
It's a local server, sorry. We properly would have to disable all mods and enable one at a time to figure out whats going on.

**Comment by greencopper** [comment]
Alright, disabled all mods, enabled one at a time and found the "gauges" mod to cause the problem for some reason.

Gauges: https://forum.minetest.net/viewtopic.php?f=11&t=10250

If "xdecor" and "gauges" are the only two mods enabled, then getting up from a chair or cushion doesn't work.

**Comment by kilbith** [comment]
Tested with this mod, can't reproduce your issue.

**Comment by greencopper** [comment]
This is on a server, not client.

**Comment by greencopper** [comment]
We have all mods enable except gauges, then xdecor works, but take a look at the shot. This is after gauges has been disabled.
![shot](https://cloud.githubusercontent.com/assets/1302896/13127278/cf240d8c-d5ce-11e5-826b-5dd0e0fa4b9b.png)

**Comment by greencopper** [comment]
We have also just tested on a 0.4.13 single player client. With only "xdecor" and "gauges" mods installed, getting up from a cushion or chair doesn't work.

**Comment by kilbith** [comment]
Ah, I see now. That's because you can't sit or get up on a chair/cushion if there is an entity close to. This prevents to sit if there is already another player sit at the same place.

**Comment by greencopper** [comment]
Ah, that makes sense :) Alright, at least the problem is known now :) Thanks for your time. Great mod!
