### ISSUE TITLE
bug de pressure si + d'une porte

### ISSUE THREAD

**Issue by crabman77** [kilbith/xdecor#34]
Dans mechanisms.lua ligne 33, pour chaque porte trouvée la fonction door_toggle est lancée, ligne 6 elle check le nom du node, place un pressure_on puis le replace après 2 secondes par un _off, sauf que si il y a + d'une porte, la 1ère place un pressure_on, la 2ème trouve donc un pressure on, du coup elle replace un pressure_on.
C'est aussi lancé pour chaque player trouvés.

un 2eme bug/usebug, si entre temps on dig le pressure, vu qu'il est replacé après 2 secondes on peut récupérer un stack de pressure.

**Comment by kilbith** [comment]
https://github.com/kilbith/xdecor/commit/68a5559a291e50ed4998625cc7fca91105f9780d
