### ISSUE TITLE
cauldron/bucket bug

### ISSUE THREAD

**Issue by crabman77** [kilbith/xdecor#35]
La fonction "cauldron.filling" sert pour le cauldron vide et le plein d'eau, mais n'a aucun test pour savoir si on a un bucket vide ou plein en fonction du cauldron, si on click sur un cauldron vide avec un bucket vide le bucket est rempli.
Si on a plusieurs bucket vide empilés ils sont tous remplacer par un seul plein.

**Comment by kilbith** [comment]
https://github.com/kilbith/xdecor/commit/0133e27ef825d143f885835dc9dda5b3edf871dc

Par ailleurs merci de communiquer en français correct, j'ai parfois du mal à décrypter le franglais...

**Comment by Ombridride** [comment]
@crabman77 ayant la gentillesse de faire un bugreport, et qui pointe à la fonction près ou ce situe le problème, ta remarque manque un peu de tact :/

Quoiqu'il en soit, merci pour le fix
