### ISSUE TITLE
server crash, ubuntu 64 vps running 4.13 dev.  simple_protection:claim in enchant table?

### ISSUE THREAD

**Issue by kingtard** [kilbith/xdecor#40]
2016-03-19 13:52:07: ACTION[Server]: amis uses simple_protection:claim, pointing at [node under=-58,-6,-9 above=-58,-5,-9]
2016-03-19 13:52:08: ACTION[Server]: amis uses simple_protection:claim, pointing at [node under=-58,-6,-9 above=-58,-6,-8]
2016-03-19 13:52:10: ERROR[Main]: ServerError: Lua: Runtime error from mod 'xdecor' in callback nodemeta_inventory_AllowPut(): /home/ubuntu/.minetest/mods/xdecor/encha$
2016-03-19 13:52:10: ERROR[Main]: stack traceback:
2016-03-19 13:52:10: ERROR[Main]:       /home/ubuntu/.minetest/mods/xdecor/enchanting.lua:86: in function 'allowed'
2016-03-19 13:52:10: ERROR[Main]:       /home/ubuntu/.minetest/mods/xdecor/enchanting.lua:95: in function </home/ubuntu/.minetest/mods/xdecor/enchanting.lua:91>

**Comment by kilbith** [comment]
No it's nothing related with the `simple_protection` mod. Some player tried to put a tool in the enchantment table and I'd like to know what it is.

**Comment by kingtard** [comment]
I could not find anything in the server log. I'm a noob, not very tech savvy.  If you can advise me on what to search for, I will try and repost.

**Comment by kilbith** [comment]
Get the list of players that was present before the server crash, and ask them who used the enchant table, maybe.

**Comment by kingtard** [comment]
I hope this helps. I had another crash with exact same error as I posted earlier. I searched logs above the error and assumed "LuaEntitySAO" may be the enchant table.  Unfortunately I see neither player speak english and return to the server recently.  Feel free to join and attempt to replicate the crash.  I have no problems with that.

last "LuaEntitySAO" before 1st crash
j3vfjev punches object 9456: LuaEntitySAO at (216.902,11.7051,-212.376)

last "LuaEntitySAO" before 2st crash
anirakeb punches object 20432: LuaEntitySAO at (227.8,16.8,-28.7083)

I teleported to the locations and found an enchantment table near.
1 contained a unmodifed default:sword_steel, with the slot for mese crystal empty.
The other area was only a empty enchantment table.

(USER INVENTORY)
breath = 11
hp = 0
name = j3vfjev
pitch = 15
position = (2097.12,115,-2191.92)
version = 1
yaw = 292.1
PlayerArgsEnd
List main 32
Width 0
Empty
Item default:enchanted_pick_diamond_durable
Item default:torch 99
Empty
Empty
Item default:wood 99
Item farming:bread 20
Item default:gold_ingot 20
Empty
breath = 11
hp = 0
name = j3vfjev
pitch = 15
position = (2097.12,115,-2191.92)
version = 1
yaw = 292.1
PlayerArgsEnd
List main 32
Width 0
Empty
Item default:enchanted_pick_diamond_durable
Item default:torch 99
Empty
Empty
Item default:wood 99
Item farming:bread 20
Item default:gold_ingot 20
Empty
Empty
Empty
Empty
Empty
EndInventoryList
List craft 9
Width 3
Empty
Empty
EndInventoryList
List craftpreview 1
Width 0
Empty
EndInventoryList
List craftresult 1
Width 0
Empty
EndInventoryList
List more_chests:wifi 32
Width 0
Empty
Empty
Empty
EndInventoryList
List bag1 1
Width 0
Empty
List bag2 1
Width 0
Empty
EndInventoryList
List bag3 1
Width 0
Empty
EndInventoryList
List bag4 1
Width 0
Empty
EndInventoryList
List enderchest 32
Width 0
Empty
Empty
Empty
E
List bag2 1
Width 0
Empty
EndInventoryList
List bag3 1
Width 0
Empty
EndInventoryList
List bag4 1
Width 0
Empty
EndInventoryList
List enderchest 32
Width 0
Empty
Empty
Empty
E
EndInventoryList
List bag2 1
Width 0
 Empty
Empty
Empty
EndInventoryList
EndInventory

(USER INVENTORY 2)
breath = 11
hp = 20
name = anirakeb
pitch = 0.6
position = (2269.84,165,-243.09)
version = 1
yaw = 321.29
PlayerArgsEnd
List main 32
Width 0
Item default:enchanted_sword_steel_sharp 1 2184
Item default:pick_diamond 1 27340
Item default:torch 2
Item default:wood 95
Item default:stick 4
Item default:wood
Item default:wood 9
Item default:sword_stone
Empty
Item default:dirt 6
Item default:steel_ingot
Item default:gold_lump 6
Item default:copper_lump 4
Item default:desert_cobble 25
Item farming:bread 5
Item default:wood 4
Item default:coal_lump 5
Item default:steel_ingot
Item default:steel_ingot
Item default:steel_ingot
Item default:leaves 17
Item default:steel_ingot
Item default:gold_ingot 20
Item default:desert_sand 2
Item default:cobble 99
Item default:gravel 5
Item default:steel_ingot
Item default:steel_ingot
Empty
Item default:sapling 2
Empty
EndInventoryList
List craft 9
Width 3
Empty
Item default:gravel 5
Item default:steel_ingot
Item default:steel_ingot
Empty
Item default:sapling 2
Empty
EndInventoryList
List craft 9
Width 3
Empty
Item default:gravel 5
Item default:steel_ingot
Item default:steel_ingot
Empty
Item default:sapling 2
Empty
EndInventoryList
List craft 9
Width 3
Empty
EndInventoryList
List bag1 1
Width 0
Empty
EndInventoryList
List bag2 1
Width 0
ist bag2 1
Width 0
Empty
EndInventoryList
List bag3 1
Width 0
Empty
EndInventoryList
List bag4 1
Width 0
Empty
EndInventoryList
List enderchest 32
Width 0
ist bag2 1
Width 0
Empty
EndInventoryList
List bag3 1
Width 0
Empty
EndInventoryList
List bag4 1
Width 0
Empty
EndInventoryList
List enderchest 32
Width 0
Width 0
Empty
Empty
Empty
Empty
Empty
Empty
EndInventoryList
EndInventory

**Comment by kilbith** [comment]
Thanks for the infos.

The enchant table is a node, not an entity (like a player or dropped items). I really have no idea what triggers these crashes or if it's really related to the enchant table.

I'll leave this issue opened for a bunch of days in case I have further infos.
