### ISSUE TITLE
Trampolines look messed up

### ISSUE THREAD

**Issue by Napiophelios** [kilbith/xdecor#42]
Trampolines look messed up 
using the blank mailbox texture

![screenshot_20160424_171533](https://cloud.githubusercontent.com/assets/8119411/14770576/e6679b5a-0a42-11e6-898f-0a79a18210eb.png)

**Comment by kilbith** [comment]
I know, that's on purpose because there's an empty space between the legs and it's a single nodebox. Anyways the end-user never (or very rarely) looks under a trampoline.
