### ISSUE TITLE
Tools are repaired when enchanted

### ISSUE THREAD

**Issue by wischi-chr** [kilbith/xdecor#8]
is this intentional or a bug?

**Comment by kilbith** [comment]
You mean when the enchanted tools are put into the Work Table for getting repaired ?

**Comment by wischi-chr** [comment]
No. Put a (vanilla) worn tool into the enchanting table and enchant it. This also repairs the item.

**Comment by kilbith** [comment]
Yes indeed, this isn't intentional...

**Comment by wischi-chr** [comment]
sorry misread "isn't" :smile:

**Comment by kilbith** [comment]
I'm looking into the API to get the current wear of the tool in the inputstack, and set the same wear for the enchanted one that replaces it.

**Comment by kilbith** [comment]
OK fixed with https://github.com/kilbith/xdecor/commit/c4d16ad2dfb6348d7758499b51ee4fc0a9a4f9ad

Thanks for the report.
