### ISSUE TITLE
xwalls are not connected

### ISSUE THREAD

**Issue by wischi-chr** [kilbith/xdecor#9]
this first occured in 9d31ec93e6df7028ecfa6cc2d6a331ee7fd18733 .
Steps to reproduce:

1.) checkout 0a1e65b766d63234e514ad0e69725fe10c4c211c 
2.) place some xwall nodes -> they connect to each other
3.) checkout 9d31ec93e6df7028ecfa6cc2d6a331ee7fd18733
4.) place some xwalls; they do no longer connect to one another

**Comment by kilbith** [comment]
Ah dammit, I should have checked this trivial change. Thanks.

Fixed : https://github.com/kilbith/xdecor/commit/193e69b577a30102690e2ef16ddb4ca2142b9c6d
